### ISSUE TITLE
Shorter naming

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AndreyAkinshin/BlittableStructs#2]
`BlittableStucts.BlittableBoolean` -> `Blittable.Bool`?
`BlittableStucts.BlittableBoolean` -> `Blittable.Boolean`?

If I wan to replace `boolean` into `BlittableStucts.BlittableBoolean` in my API I hope to make calls shorter (with no need to repeat `Blittable` twice).

**Comment by AndreyAkinshin** [comment]
@dzmitry-lahoda, sorry for the late response.

`BlittableStructs` is a namespace, so you can write

```
using BlittableStructs;
```

and use `BlittableBoolean` without the `BlittableStucts.` prefix.

I don't want to rename `BlittableBoolean` to `Boolean` because it will conflict with `System.Boolean`.

**Comment by dzmitry-lahoda** [comment]
`Structs` in `BlittableStructs` seems still may be excessive as unprobably to have blittable classes.

I want to use blittable boolean, ideally it could be in `System` namespace to avoid referencing namespace, but change change `bool` into `BlittableBoolean`.

**Comment by AndreyAkinshin** [comment]
I'm not going to move `BlittableBoolean` to the `System` namespace because this namespace is designed for system structs and classes. 3rdParty libraries should have own namespaces.
If you don't like long titles, you can introduce aliases like this:

```cs
using Bool=BlittableStructs.BlittableBoolean;
```

Also, you are free to fork this library and make changes that you need. Or you can just copy-paste relevant classes to your project and change namespace and struct names as you want.
